export const countryFlags: Record<string, string> = {
  "USA": "🇺🇸",
  "United States": "🇺🇸",
  "US": "🇺🇸",
  "UK": "🇬🇧",
  "United Kingdom": "🇬🇧",
  "Great Britain": "🇬🇧",
  "England": "🇬🇧",
  "Switzerland": "🇨🇭",
  "Germany": "🇩🇪",
  "France": "🇫🇷",
  "Japan": "🇯🇵",
  "China": "🇨🇳",
  "Italy": "🇮🇹",
  "Netherlands": "🇳🇱",
  "Sweden": "🇸🇪",
  "South Korea": "🇰🇷",
  "Brazil": "🇧🇷",
  "India": "🇮🇳",
  "Canada": "🇨🇦",
  "Australia": "🇦🇺",
  "Spain": "🇪🇸",
  "Belgium": "🇧🇪",
  "Austria": "🇦🇹",
  "Denmark": "🇩🇰",
  "Norway": "🇳🇴",
  "Finland": "🇫🇮",
  "Poland": "🇵🇱",
  "Czech Republic": "🇨🇿",
  "Hungary": "🇭🇺",
  "Romania": "🇷🇴",
  "Bulgaria": "🇧🇬",
  "Greece": "🇬🇷",
  "Portugal": "🇵🇹",
  "Ireland": "🇮🇪",
  "Luxembourg": "🇱🇺",
  "Singapore": "🇸🇬",
  "Hong Kong": "🇭🇰",
  "Taiwan": "🇹🇼",
  "South Africa": "🇿🇦",
  "Mexico": "🇲🇽",
  "Argentina": "🇦🇷",
  "Chile": "🇨🇱",
  "Colombia": "🇨🇴",
  "Peru": "🇵🇪",
  "Venezuela": "🇻🇪",
  "Uruguay": "🇺🇾",
  "Paraguay": "🇵🇾",
  "Bolivia": "🇧🇴",
  "Ecuador": "🇪🇨",
  "New Zealand": "🇳🇿",
  "Thailand": "🇹🇭",
  "Vietnam": "🇻🇳",
  "Malaysia": "🇲🇾",
  "Indonesia": "🇮🇩",
  "Philippines": "🇵🇭",
  "Pakistan": "🇵🇰",
  "Bangladesh": "🇧🇩",
  "Sri Lanka": "🇱🇰",
  "Nepal": "🇳🇵",
  "Myanmar": "🇲🇲",
  "Cambodia": "🇰🇭",
  "Laos": "🇱🇦",
  "Mongolia": "🇲🇳",
  "Kazakhstan": "🇰🇿",
  "Uzbekistan": "🇺🇿",
  "Kyrgyzstan": "🇰🇬",
  "Tajikistan": "🇹🇯",
  "Turkmenistan": "🇹🇲",
  "Azerbaijan": "🇦🇿",
  "Georgia": "🇬🇪",
  "Armenia": "🇦🇲",
  "Ukraine": "🇺🇦",
  "Belarus": "🇧🇾",
  "Moldova": "🇲🇩",
  "Latvia": "🇱🇻",
  "Lithuania": "🇱🇹",
  "Estonia": "🇪🇪",
  "Slovenia": "🇸🇮",
  "Croatia": "🇭🇷",
  "Serbia": "🇷🇸",
  "Bosnia and Herzegovina": "🇧🇦",
  "Montenegro": "🇲🇪",
  "North Macedonia": "🇲🇰",
  "Albania": "🇦🇱",
  "Kosovo": "🇽🇰",
  "Iceland": "🇮🇸",
  "Malta": "🇲🇹",
  "Cyprus": "🇨🇾",
  "Israel": "🇮🇱",
  "Lebanon": "🇱🇧",
  "Jordan": "🇯🇴",
  "Syria": "🇸🇾",
  "Iraq": "🇮🇶",
  "Iran": "🇮🇷",
  "Afghanistan": "🇦🇫",
  "Turkey": "🇹🇷",
  "Saudi Arabia": "🇸🇦",
  "Yemen": "🇾🇪",
  "Oman": "🇴🇲",
  "UAE": "🇦🇪",
  "United Arab Emirates": "🇦🇪",
  "Qatar": "🇶🇦",
  "Kuwait": "🇰🇼",
  "Bahrain": "🇧🇭",
  "Egypt": "🇪🇬",
  "Libya": "🇱🇾",
  "Tunisia": "🇹🇳",
  "Algeria": "🇩🇿",
  "Morocco": "🇲🇦",
  "Sudan": "🇸🇩",
  "South Sudan": "🇸🇸",
  "Ethiopia": "🇪🇹",
  "Eritrea": "🇪🇷",
  "Djibouti": "🇩🇯",
  "Somalia": "🇸🇴",
  "Kenya": "🇰🇪",
  "Uganda": "🇺🇬",
  "Tanzania": "🇹🇿",
  "Rwanda": "🇷🇼",
  "Burundi": "🇧🇮",
  "DR Congo": "🇨🇩",
  "Congo": "🇨🇬",
  "Gabon": "🇬🇦",
  "Cameroon": "🇨🇲",
  "Central African Republic": "🇨🇫",
  "Chad": "🇹🇩",
  "Niger": "🇳🇪",
  "Mali": "🇲🇱",
  "Burkina Faso": "🇧🇫",
  "Senegal": "🇸🇳",
  "Gambia": "🇬🇲",
  "Guinea-Bissau": "🇬🇼",
  "Guinea": "🇬🇳",
  "Sierra Leone": "🇸🇱",
  "Liberia": "🇱🇷",
  "Côte d'Ivoire": "🇨🇮",
  "Ghana": "🇬🇭",
  "Togo": "🇹🇬",
  "Benin": "🇧🇯",
  "Nigeria": "🇳🇬"
}; 